CREATE TABLE `ap`.`catalogounidadadministrativa` (
  `idCatalogoUnidadAdministrativa` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`idCatalodoUnidadAdministrativa`));


insert into catalogoUnidadAdministrativa (descripcion) values("OFICINA DEL GOBERNADOR");
insert into catalogoUnidadAdministrativa (descripcion) values("PROCURADURÍA DE PROTECCIÓN AL AMBIENTE DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DE EDUCACIÓN");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DE MOVILIDAD");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA TÉCNICA DEL GABINETE");
insert into catalogoUnidadAdministrativa (descripcion) values("BANCO DE TEJIDOS DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("CENTRO DE CONTROL DE CONFIANZA DEL ESTADO DE MEXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("COLEGIO DE BACHILLERES DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("COLEGIO DE ESTUDIOS CIENTÍFICOS Y TECNOLÓGICOS DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("COMISIÓN DE CONCILIACIÓN Y ARBITRAJE MÉDICO DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("COMISIÓN DEL AGUA DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("COMISIÓN ESTATAL DE PARQUES NATURALES Y DE LA FAUNA");
insert into catalogoUnidadAdministrativa (descripcion) values("COMISIÓN PARA EL DESARROLLO TURÍSTICO DEL VALLE DE TEOTIHUACÁN");
insert into catalogoUnidadAdministrativa (descripcion) values("COMISION TECNICA DEL AGUA DEL ESTADO DE MEXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("COMITÉ DE PLANEACIÓN PARA EL DESARROLLO DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("CONSEJO DE INVESTIGACIÓN Y EVALUACIÓN DE LA POLÍTICA SOCIAL");
insert into catalogoUnidadAdministrativa (descripcion) values("CONSEJO ESTATAL DE LA MUJER Y BIENESTAR SOCIAL DEL ESTADO DE MEXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("CONSEJO ESTATAL PARA EL DESARROLLO INTEGRAL DE LOS PUEBLOS INDÍGENAS DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("CONSEJO MEXIQUENSE DE CIENCIA Y TECNOLOGÍA");
insert into catalogoUnidadAdministrativa (descripcion) values("COORDINACIÓN GENERAL DE COMUNICACIÓN SOCIAL");
insert into catalogoUnidadAdministrativa (descripcion) values("FIDEICOMISO PARA EL DESARROLLO DE PARQUES Y ZONAS INDUSTRIALES EN EL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("FIDEICOMISO PÚBLICO PARA LA CONSTRUCCIÓN DE CENTROS PREVENTIVOS Y READAPTACIÓN SOCIAL EN EL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("FISCALIA GENERAL DE JUSTICIA");
insert into catalogoUnidadAdministrativa (descripcion) values("HOSPITAL REGIONAL DE ALTA ESPECIALIDAD DE ZUMPANGO");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO DE CAPACITACIÓN Y ADIESTRAMIENTO PARA EL TRABAJO INDUSTRIAL");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO DE FOMENTO MINERO Y ESTUDIOS GEOLÓGICOS DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO DE INFORMACIÓN E INVESTIGACIÓN GEOGRÁFICA, ESTADÍSTICA Y CATASTRAL DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO DE INVESTIGACIÓN Y CAPACITACIÓN AGROPECUARIA, ACUÍCOLA Y FORESTAL DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO DE INVESTIGACION Y FOMENTO DE LAS ARTESANIAS");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO DE LA FUNCIÓN REGISTRAL DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO DE SEGURIDAD SOCIAL DEL ESTADO DE MEXICO Y MUNICIPIOS");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO ESTATAL DE ENERGIA Y CAMBIO CLIMATICO");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO HACENDARIO DEL ESTADO DE  MEXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO MATERNO INFANTIL DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO MEXIQUENSE DE LA INFRAESTRUCTURA FÍSICA EDUCATIVA");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO MEXIQUENSE DE LA JUVENTUD");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO MEXIQUENSE DE LA PIROTÉCNIA");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO MEXIQUENSE DE LA VIVIENDA SOCIAL");
insert into catalogoUnidadAdministrativa (descripcion) values("INSTITUTO MEXIQUENSE DEL EMPRENDEDOR");
insert into catalogoUnidadAdministrativa (descripcion) values("JUNTA DE ASISTENCIA PRIVADA DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("JUNTA DE CAMINOS DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("JUNTA LOCAL DE CONCILIACION Y ARBITRAJE DEL VALLE DE CUAUT-TEX");
insert into catalogoUnidadAdministrativa (descripcion) values("JUNTA LOCAL DE CONCILIACION Y ARBITRAJE DEL VALLE DE TOLUCA");
insert into catalogoUnidadAdministrativa (descripcion) values("PROCURADURIA DEL COLONO DEL ESTADO DE MEXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("PROTECTORA DE BOSQUES");
insert into catalogoUnidadAdministrativa (descripcion) values("RECICLAGUA AMBIENTAL, S.A. DE C.V.");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARIA DE COMUNICACIONES");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARIA DE CULTURA");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DE DESARROLLO AGROPECUARIO");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DE DESARROLLO ECONÓMICO");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DE DESARROLLO SOCIAL");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DE DESARROLLO URBANO Y METROPOLITANO");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DE FINANZAS");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARIA DE JUSTICIA Y DERECHOS HUMANOS");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DE LA CONTRALORÍA");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARIA DE OBRA PUBLICA");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARIA DE SALUD");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARIA DE SEGURIDAD");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DE TURISMO");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DEL MEDIO AMBIENTE");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA DEL TRABAJO");
insert into catalogoUnidadAdministrativa (descripcion) values("SECRETARÍA GENERAL DE GOBIERNO");
insert into catalogoUnidadAdministrativa (descripcion) values("SERVICIOS EDUCATIVOS INTEGRADOS AL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("SISTEMA DE AUTOPISTAS, AEROPUERTOS, SERVICIOS CONEXOS Y AUXILIARES DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("SISTEMA DE RADIO Y TELEVISIÓN MEXIQUENSE");
insert into catalogoUnidadAdministrativa (descripcion) values("SISTEMA DE TRANSPORTE MASIVO Y TELEFÉRICO DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("SISTEMA ESTATAL ANTICORRUPCIÓN");
insert into catalogoUnidadAdministrativa (descripcion) values("SISTEMA PARA EL DESARROLLO INTEGRAL DE LA FAMILIA DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE CHALCO");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE CHIMALHUACÁN");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE COACALCO");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE CUAUTITLÁN IZCALLI");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE ECATEPEC");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE HUIXQUILUCAN");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLOGICO DE ESTUDIOS SUPERIORES DE IXTAPALUCA");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE JILOTEPEC");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE JOCOTITLÁN");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE SAN FELIPE DEL PROGRESO");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE TIANGUISTENCO");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE VALLE DE BRAVO");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DE VILLA GUERRERO");
insert into catalogoUnidadAdministrativa (descripcion) values("TECNOLÓGICO DE ESTUDIOS SUPERIORES DEL ORIENTE DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("TRIBUNAL DE JUSTICIA ADMINISTRATIVA DEL ESTADO DE MEXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("TRIBUNAL ESTATAL DE CONCILIACION Y ARBITRAJE ");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIDAD DE APOYO A LA ADMINISTRACIÓN GENERAL/ SECRETARÍA DE FINANZAS ");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIDAD DE ASUNTOS INTERNOS");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD DIGITAL DEL ESTADO DE MEXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD ESTATAL DEL VALLE DE ECATEPEC");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD ESTATAL DEL VALLE DE TOLUCA");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD INTERCULTURAL DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD MEXIQUENSE DEL BICENTENARIO");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD POLITÉCNICA DE ATLAUTLA");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD POLITÉCNICA DE CUAUTITLÁN IZCALLI");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD POLITÉCNICA DE OTZOLOTEPEC");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD POLITÉCNICA DE TECAMAC");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD POLITÉCNICA DE TEXCOCO");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD POLITÉCNICA DEL VALLE DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD POLITÉCNICA DEL VALLE DE TOLUCA");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD TECNOLÓGICA DE NEZAHUALCÓYOTL");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD TECNOLÓGICA DE TECÁMAC");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD TECNOLÓGICA DE ZINACANTEPEC");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD TECNOLÓGICA DEL SUR DEL ESTADO DE MÉXICO");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD TECNOLÓGICA DEL VALLE DE TOLUCA");
insert into catalogoUnidadAdministrativa (descripcion) values("UNIVERSIDAD TECNOLÓGICA FIDEL VELÁZQUEZ");
										 

