jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.connectionProperty=jdbc:mysql://
jdbc.schema=AP
jdbc.stringAditional=useSSL=false&allowPublicKeyRetrieval=True&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
jdbc.port=3306
jdbc.ip=localhost
jdbc.enviroment=PROD
jdbc.username=root
jdbc.password=root
jdbc.maxPoolSize=50
jdbc.minPoolSize=10
jdbc.maxStatements=100
jdbc.testConnection=true
jdbc.acquireIncrement = 1
jdbc.initialPoolSize= 0
jdbc.acquireRetryAttempts = 2
jdbc.breakAfterAcquireFailure = true
jdbc.statementCacheNumDeferredCloseThreads = 5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
server.servlet.session.timeout=5