handlers = java.util.logging.FileHandler
#indicates  that the sever  has problems to start
java.util.logging.FileHandler.level = SEVERE
java.util.logging.FileHandler.encoding = UTF-8
#limit to 50MB (in bytes)
java.util.logging.FileHandler.limit = 50000000
java.util.logging.FileHandler.append = true
java.util.logging.FileHandler.count = 100
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
#Windows 
java.util.logging.FileHandler.pattern = C:/CFSLOG/miLog.%g.log
#Debian
#java.util.logging.FileHandler.pattern = /log/SmartBilling.%g.log
#Info level, use only on development envirements
#java.util.logging.ConsoleHandler.level = INFO
#print all messages
#java.util.logging.ConsoleHandler.level = ALL
#Error level
java.util.logging.ConsoleHandler.level = SEVERE
#Debug level
#java.util.logging.ConsoleHandler.level = FINE