# DEFAULT ROOT PROFILE
profile.admin.name=root
profile.admin.password=5f4dcc3b5aa765d61d8327deb882cf99
profile.admin.tipo.acceso=11
#4ae33445313a0cef2a17b57ea1d45cb6 = ROLE_ADMIN
profile.admin.role=ROOT
profile.admin.descripcion=PERFIL ROOT
profile.admin.view = Administracionweb
#ADMIN AP DEFAULT
defaultAdminAP.nombreRol=ADMAP
defaultAdminAP.descripcionRol=PERFIL ADMIN AP
defaultAdminAP.usuario=XAXX010101000
defaultAdminAP.password=5f4dcc3b5aa765d61d8327deb882cf99
defaultAdminAP.tipoAcceso=11
# DEFAULT VIEWS WHICH CAN LOGGED IN PROFILES ACCESS
deault.view.url = /angular2,/acceso/menu

#DEFAULT VIEWS FOR PROFILES
default.access.list={'GERENTE': {'dashboard-1'},\
'ADMIN': {'dashboard'}}
user.access.tipo.value={'ROOT':0,'CUADRILLA':1,'SUPERVISOR':11,'TRABAJADOR DE CAMPO':1}

default.access.solicitudes.versolicitudes={'PM':'P',\
'ALMACENISTA':'A',\ 'EJECUTIVO': 'E'}
#DEFAULT PROFILES INIT
profile.profile.types = ROOT
# CAMBIO CONTEXT
#Contexto local
#context.app_name = AP
#context.server = 127.0.0.1:8080
#context.properties=properties
#context.http=http://
#Contexto despliegue QA 
#context.app_name = AP
#context.server = 34.200.128.17:8080
#context.properties=properties
#context.http=http://
#Contexto despliegue prod
context.app_name = AP
context.server = 54.215.98.76:8080
context.properties=properties
context.http=http://
#Contexto despliegue prepro
#context.app_name = AP
#context.server = 54.153.12.83:8080
#context.properties=properties
#context.http=http://
#Firebase Local
firebase.database.url=https://adbp-a638e-default-rtdb.firebaseio.com/

